[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "n3kQw9v8z1JpL6x2V7sT4r5y8u0aBcDeFgHiJkLmNoPqRsTuVwXyZ"
client_id = "412694488935-4gbin86tsv1834dlr6pjbe6guq8uelj8.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"